### ISSUE TITLE
[AVL-43] Create Documentation for DeviceRegistry 

### ISSUE THREAD

**Issue by h-ostcode** [hatfield-c/avl#43]
Create documentation for DeviceRegistry class of EgoVehicle.  Include how the DeviceRegistry is passed on to each Task, what each float array is (functionality and what data is stored), and how to read sensor data using the DeviceRegistry.

**Comment by h-ostcode** [comment]
Completed first portion of documentation for Device Registry Class, including brief overview, description of how Device Registry interacts with Tasks, and descriptions of sensor memory float arrays. Uploaded to UTD-RTOS folder. HJO.

**Comment by hatfield-c** [comment]
I have updated the device registry documentation, and have completed it. Thus this issue is complete, and will be closed.
