### ISSUE TITLE
[AVL-46] Update README with quick start and installation instructions

### ISSUE THREAD

**Issue by hatfield-c** [hatfield-c/avl#46]
The README in the repo is still for the old version of AVL. This should be updated such that it gives students step-by-step instructions for installing the AVL project and opening it with the specific Unity version that has been approved for the AVL. There should also be instructions for a sample scene for students to confirm that the AVL project works as intended.

**Comment by hatfield-c** [comment]
The following sections need to be in the README:
- Introduction : Briefly explain in a paragraph what the AVL is, and what it is meant to be used for
- Requirements : List the Unity version currently being used, and any other requirements you might think are relevant.
- Unity Installation : List the steps necessary to install the *specific* Unity version listed in requirements. Unity will likely be updated to newer versions as time goes on, but we can only guarantee stability with the version we currently use.
- Project Installation : List the steps necessary to download the project from github (without using git, as students might not know how to use git). Also describe how to set up the project to be used in Unity
- Quick Start Guide : Explain how to open the Playground scene file, and explain how to control the Ego vehicle with the keyboard

You'll need to test your instructions extensively. So practice following your own instructions, and redownload project files to make sure there are no issues. Tagging @hjostoja so she gets the notification.

**Comment by h-ostcode** [comment]
README.md has been updated and final edits made. This is now complete.
